### ISSUE TITLE
Force-enable body overflow

### ISSUE THREAD

**Issue by indrekpaas** [micmro/performance-bookmarklet#28]
Some sites/web apps disable body overflow by default. This won't allow to scroll the overflowing results. [SVGOMG](https://jakearchibald.github.io/svgomg/) for reference.

**Comment by micmro** [comment]
PR #27 from @mmanela will take care about this, there are just a few details I'd like to iron out before merging it.

**Comment by micmro** [comment]
Fixed in bookmarklet - will need a new release to fix it in chrome extension & firefox adon.
