### ISSUE TITLE
Data store

### ISSUE THREAD

**Issue by hunter2009** [micmro/performance-bookmarklet#36]
The project is very useful for web performance, I want to use it in my project, but I need some API to save performace data for analysing user's performace, can you give me some advise?

**Comment by hunter2009** [comment]
By the way, can you soppurt ie?

**Comment by micmro** [comment]
Sorry for the late reply, I was quite busy in the last days.

I am not sure I fully understand the question, but I give it a stab anyway :) :
To get a (real) users performance data you can store data from the Resource Timing API, Navigation Timing API and User-Timing API data (e.g. `window.performance`...) and use a tool like [Boomerang](http://www.lognormal.com/boomerang/doc/) or the new [Beacon API](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) to send it back to your server or wherever you store your logs. 

If you want to just test it synthetically you could use the awesome [WebPageTest](http://www.webpagetest.org/) and store the result as a [HAR](http://www.softwareishard.com/blog/har-12-spec/).

I hope this answers your question.

**Comment by hunter2009** [comment]
Thank you, @micmro .It's hopeful to me.
I want use it in my project because it's really a useful tool, but I want to save users' data in production line,and I hope you can provide a API to implement it.

**Comment by micmro** [comment]
I'm in Korea it's not such a different time zone ;).

Sorry I don't understand how this should work, `performance-bookmarklet` is a bookmarklet for the local performant measurements, it's not installed in the site. 
Would you want to get your users to install it and see their requests performance metrics or do you just want to collect data and visualize it centrally? If the second is the case I don't think this is the right solution for you.

**Comment by hunter2009** [comment]
I'm busy because I upgrade babel from 5 to 6, and causing many problems.
I want to collect users' data by inserting your js file and user don't need to install any plugins in their browsers.
