### ISSUE TITLE
Does performance analyser support pages that have more than 150 requests?

### ISSUE THREAD

**Issue by johnapclaw** [micmro/performance-bookmarklet#38]
Hello,  

Thank you for creating such a handy tool.   Does it support a page that has more than 150 requests?

Thank,
John

**Comment by micmro** [comment]
Hi John,

I have not tested it but I am not aware of any restrictions regarding the number of requests.
Did you have any issues with this?

Michael

**Comment by hunter2009** [comment]
I had same question, but it doesn't matter with the tool, the reason is onresourcetimingbufferfull, performance only can support 150 requests, and I don't get any idea about it, so I hope you can give me some advise, @micmro 
Simon

**Comment by stefounet** [comment]
See https://developer.mozilla.org/en-US/docs/Web/API/Resource_Timing_API/Using_the_Resource_Timing_API#Managing_the_resource_buffer

**Comment by micmro** [comment]
Thanks a lot for clarifying @stefounet.

_For future reference:_
The [Resource Timing Buffer](https://developer.mozilla.org/en-US/docs/Web/API/Resource_Timing_API/Using_the_Resource_Timing_API#Managing_the_resource_buffer) only supports 150 entries (if not modified).

performance-bookmarklet would need to either change the Resource Timing Buffer size or (better) use the [PerformanceObserver](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceObserver). As both would need to be done early in the page load cycle it is not something I'd like to for performance-analyser nor can I do for performance-bookmarklet.
