### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by erotavlas85** [micmro/performance-bookmarklet#49]
Hi,
is the add on still available for firefox? The links are broken and I could not find it.
Thank you

**Comment by micmro** [comment]
Thanks for the heads up. Looks like it is not available anymore and I will have to re-publish it with new settings. In the meantime you can still use it as a bookmarklet.

**Comment by micmro** [comment]
Sorry it took so long - it's uploaded again:
https://addons.mozilla.org/en/firefox/addon/performance-analyser
