### ISSUE TITLE
ssl/tls value seems to be incorrectly calculated

### ISSUE THREAD

**Issue by tannaga** [micmro/performance-bookmarklet#55]
Based on my research, ssl/tls value is the diff of `connectEnd-secureConnectionStart`. Looks like in this repo, it is calculated using connectStart.

```
	if(perfTimingCalc.secureConnectionStart){
		perfTimingCalc.blocks.push(waterfall.timeBlock("SSL", perfTimingCalc.connectStart, perfTimingCalc.secureConnectionStart, "block-ssl"));
	}
```
Let me know your thoughts. I am open to submitting a PR if this needs to be fixed.

**Comment by micmro** [comment]
Thanks a lot @tannaga! Wow, great catch - this is a serious bug. I fixed the issue in the bookmarklet and issues an update request for the chrome and firefox extensions.

**Comment by tannaga** [comment]
thank you for the quick turnaround.
